// ===== 島キャンプ思い出マップ : 初期データ（シード） =====
// ここを編集すれば初期表示の島・内容を増やせます。
// アプリ上で追加・編集した内容は端末に保存され、共有設定時は5人で同期されます。
// spots: 各島の有名スポット（Web調査で座標検証済み・2026-07）。
//   cat は キャンプ場/ビーチ/温泉/山・自然/観光/食事・店/港・交通 のいずれか。
// 写真は端末内(IndexedDB)に保存されるため、ここには書きません。

window.SEED_ISLANDS = [
  {
    id: "izu-oshima", name: "大島", region: "伊豆諸島", pref: "東京都",
    lat: 34.75, lng: 139.36,
    firstVisit: "2005", visits: 12, fav: true,
    summary: "三原山と椿。伊豆諸島の玄関口。ジェット船で最短。",
    photos: [],
    spots: [
      { name: "トウシキキャンプ場", cat: "キャンプ場", lat: 34.6812, lng: 139.43,
        url: "https://www.town.oshima.tokyo.jp/soshiki/kankou/toshiki-camp.html",
        note: "無料の町営キャンプ場。溶岩海岸の絶景とトウシキ遊泳場が目前" },
      { name: "海のふるさと村", cat: "キャンプ場", lat: 34.7462, lng: 139.4445,
        url: "https://umifuru.tokaikisen.co.jp/",
        note: "東海岸の設備充実キャンプ場。ロッジやデッキテントも。要予約" },
      { name: "弘法浜", cat: "ビーチ", lat: 34.7459, lng: 139.3538,
        url: "https://www.town.oshima.tokyo.jp/soshiki/kankou/koubouhamapool.html",
        note: "元町港至近の黒砂ビーチ。島の代表的な海水浴場でプール併設" },
      { name: "秋の浜", cat: "ビーチ", lat: 34.786, lng: 139.4045,
        url: "https://oshima-navi.com/diving/index.html",
        note: "島随一のダイビングスポット。透明度が高くシュノーケルも人気" },
      { name: "砂の浜", cat: "ビーチ", lat: 34.695, lng: 139.3828,
        url: "https://www.oshima-navi.com/geopark/sanohama.html",
        note: "黒い玄武岩の砂浜が約1km続く日本の渚百選。遊泳は非推奨" },
      { name: "愛らんどセンター御神火温泉", cat: "温泉", lat: 34.7566, lng: 139.3512,
        url: "https://www.town.oshima.tokyo.jp/soshiki/kankou/gojinka.html",
        note: "元町港近くの日帰り温泉施設。早朝営業で船待ちにも便利" },
      { name: "大島温泉 元町浜の湯", cat: "温泉", lat: 34.7545, lng: 139.352,
        url: "https://www.town.oshima.tokyo.jp/soshiki/kankou/hamanoyu.html",
        note: "水着で入る混浴露天風呂。伊豆半島に沈む夕日と富士山を一望" },
      { name: "三原山温泉 大島温泉ホテル", cat: "温泉", lat: 34.7537, lng: 139.4019,
        url: "https://www.oshima-onsen.co.jp/",
        note: "原生林越しに三原山を望む絶景露天風呂。日帰り入浴も可能" },
      { name: "三原山", cat: "山・自然", lat: 34.7245, lng: 139.3944,
        url: "https://www.gotokyo.org/jp/spot/253/index.html",
        note: "標高758mの活火山。お鉢巡りで火口を一周できる島のシンボル" },
      { name: "裏砂漠", cat: "山・自然", lat: 34.7319, lng: 139.4144,
        url: "https://oshima-navi.com/urasabaku/",
        note: "国内で唯一地図に「砂漠」と載る黒いスコリアの大地" },
      { name: "地層大切断面", cat: "山・自然", lat: 34.7032, lng: 139.3719,
        url: "https://oshima-navi.com/geopark/stratum.html",
        note: "高さ約24m・長さ約630mの地層縞模様。通称バウムクーヘン" },
      { name: "筆島", cat: "山・自然", lat: 34.7064, lng: 139.4451,
        url: "https://www.town.oshima.tokyo.jp/soshiki/kankou/fudeshima.html",
        note: "海中に突き立つ高さ約30mの奇岩。古い火山の火道の名残" },
      { name: "泉津の切通し", cat: "観光", lat: 34.7805, lng: 139.4197,
        url: "https://oshima-navi.com/senzu/index.html",
        note: "巨木の根が両脇から迫る苔むした石段の旧道。神秘的な撮影名所" },
      { name: "東京都立大島公園 椿園", cat: "観光", lat: 34.7617, lng: 139.4359,
        url: "https://www.soumu.metro.tokyo.lg.jp/11osima/osima/park/gardens/camellia",
        note: "約1000品種の国内最大級の椿園。国際優秀つばき園に認定" },
      { name: "波浮港", cat: "観光", lat: 34.6868, lng: 139.4397,
        url: "https://www.town.oshima.tokyo.jp/soshiki/kankou/habu-harbor.html",
        note: "火口湖起源の港町。『伊豆の踊子』ゆかりのレトロな街並み" },
      { name: "伊豆大島ミュージアム -ジオノス-", cat: "観光", lat: 34.744, lng: 139.36,
        url: "https://izuoshima-geonous.org/",
        note: "旧火山博物館が2025年7月リニューアル。火山と島の暮らしを学べる拠点" },
      { name: "港鮨", cat: "食事・店", lat: 34.687, lng: 139.4398,
        url: "https://oshima-navi.com/gourmet/gourmet_map_18.html",
        note: "波浮港の寿司店。島名物べっこう寿司の名店として知られる" },
      { name: "島京梵天", cat: "食事・店", lat: 34.6865, lng: 139.4408,
        url: "https://www.tokyovoneten.com/",
        note: "波浮港の古民家たい焼きカフェ。明日葉たい焼きが名物" },
      { name: "元町港", cat: "港・交通", lat: 34.7519, lng: 139.3525,
        url: "https://www.tokaikisen.co.jp/boarding/terminal/",
        note: "島の西の玄関口。温泉や飲食店が集まる元町の中心に位置" },
      { name: "岡田港", cat: "港・交通", lat: 34.7906, lng: 139.3906,
        url: "https://www.tokaikisen.co.jp/boarding/terminal/",
        note: "島の北の玄関口。海況により元町港と発着を使い分ける" },
      { name: "大島空港", cat: "港・交通", lat: 34.7827, lng: 139.3607,
        url: "https://www.kouwan.metro.tokyo.lg.jp/rito/tmg-airport/oshima",
        note: "調布飛行場から約25分。島の空の玄関口。愛称は東京大島かめりあ空港" }
    ],
    shops: [
          {
                "name": "べっこう寿司の店",
                "type": "食事",
                "note": "島唐辛子醤油の漬け（べっこう）が名物"
          }
    ],
    knowledge: [
          "竹芝からジェット船で約1時間45分、夜行大型船もある",
          "三原山は1986年の噴火の溶岩流がそのまま残る"
    ],
    tips: [
          "レンタルバイクがあると島内移動が圧倒的に楽",
          "椿シーズンは1〜3月、椿まつりで賑わう"
    ],
    logs: [
          {
                "date": "2005",
                "text": "初めての島キャンプ。すべてここから始まった。"
          }
    ]
  },

  {
    id: "toshima", name: "利島", region: "伊豆諸島", pref: "東京都",
    lat: 34.52, lng: 139.28,
    firstVisit: "2013", visits: 1, fav: false,
    summary: "椿に覆われた小さな円錐の島。2013年訪問。",
    photos: [],
    spots: [
      { name: "宮塚山", cat: "山・自然", lat: 34.5204, lng: 139.2793,
        url: "",
        note: "標高508m。島の大半を占める円錐峰。東西の登山口から山頂へ" },
      { name: "宮塚山展望台", cat: "山・自然", lat: 34.5217, lng: 139.2797,
        url: "",
        note: "北面の展望台。伊豆大島ごしに富士山を望む" },
      { name: "南ヶ山園地", cat: "山・自然", lat: 34.5149, lng: 139.2766,
        url: "",
        note: "島南端の園地。新島・式根島・神津島を一望。星空スポット" },
      { name: "ウスイゴウ園地", cat: "山・自然", lat: 34.5226, lng: 139.2843,
        url: "",
        note: "東側の椿林の中の園地。宮塚山東登山口に近い" },
      { name: "阿豆佐和氣命神社", cat: "観光", lat: 34.5295, lng: 139.2771,
        url: "",
        note: "式内社。集落の鎮守で境内は祭祀遺跡" },
      { name: "利島村郷土資料館", cat: "観光", lat: 34.529, lng: 139.2823,
        url: "",
        note: "椿油づくりと島の暮らし・考古資料の展示" },
      { name: "茶房かおり", cat: "食事・店", lat: 34.529, lng: 139.2787,
        url: "",
        note: "集落の喫茶。営業日は要確認" },
      { name: "てづか食堂", cat: "食事・店", lat: 34.5292, lng: 139.2778,
        url: "",
        note: "集落の食堂。営業日は要確認" },
      { name: "利島港", cat: "港・交通", lat: 34.529, lng: 139.279,
        url: "https://www.tokaikisen.co.jp/boarding/terminal/",
        note: "島唯一の港。波に弱く欠航・条件付き出航が多い" }
    ],
    shops: [],
    knowledge: [
      "約20万本の椿林が島を覆う。椿油は日本有数の生産量",
      "島にキャンプ場・海水浴場はない。宿泊は民宿のみ（数が少なく要早期予約）"
    ],
    tips: [
      "就航率が低め。欠航に備えてヘリ（東京愛らんどシャトル）も検討",
      "集落は港から急坂の上。宿の送迎を頼むと楽"
    ],
    logs: []
  },

  {
    id: "niijima", name: "新島", region: "伊豆諸島", pref: "東京都",
    lat: 34.37, lng: 139.27,
    firstVisit: "2007", visits: 9, fav: true,
    summary: "白い砂浜とコーガ石。サーフィンと無料の天然温泉。",
    photos: [],
    spots: [
      { name: "羽伏浦キャンプ場", cat: "キャンプ場", lat: 34.3797, lng: 139.2717,
        url: "https://niijima-info.jp/camp/",
        note: "島内唯一の無料キャンプ場。野外炉30基、羽伏浦海岸すぐ" },
      { name: "羽伏浦海岸", cat: "ビーチ", lat: 34.3762, lng: 139.2754,
        url: "https://www.gotokyo.org/jp/spot/244/index.html",
        note: "白砂6.5kmのロングビーチ。白亜のメインゲートはサーフィンの聖地" },
      { name: "間々下海岸", cat: "ビーチ", lat: 34.3592, lng: 139.2444,
        url: "https://niijima-info.jp/spot/2136/",
        note: "波穏やかな湾内ビーチ。鳥ヶ島を望み、まました温泉の目の前" },
      { name: "前浜海岸", cat: "ビーチ", lat: 34.381, lng: 139.2546,
        url: "",
        note: "本村集落前に続く海岸。夕日と式根島の眺めが美しい" },
      { name: "湯の浜露天温泉", cat: "温泉", lat: 34.3641, lng: 139.2425,
        url: "https://niijima-info.jp/spot/2390/",
        note: "ギリシャ神殿風の無料露天風呂。24時間・水着着用で入浴" },
      { name: "まました温泉（間々下温泉）", cat: "温泉", lat: 34.3597, lng: 139.2446,
        url: "https://niijima-info.jp/spot/2366/",
        note: "大人300円の村営温泉。羽伏浦の白砂を使う砂むし風呂も" },
      { name: "富士見峠展望台", cat: "山・自然", lat: 34.3844, lng: 139.2623,
        url: "",
        note: "島中央の高台から羽伏浦海岸と本村を一望。晴れれば富士山も" },
      { name: "宮塚山", cat: "山・自然", lat: 34.3968, lng: 139.2702,
        url: "",
        note: "新島最高峰432m。山腹の展望台から島と海を一望" },
      { name: "石山展望台（向山展望台）", cat: "山・自然", lat: 34.3517, lng: 139.2473,
        url: "https://www.niijima.com/kankou/niijima/spot/2024-0911-1647-101.html",
        note: "コーガ石採石場の白い絶景。式根島・神津島を望む" },
      { name: "淡井浦海岸", cat: "ビーチ", lat: 34.4133, lng: 139.2871,
        url: "",
        note: "北部若郷の静かな入り江。手つかずの自然が残る穴場" },
      { name: "大三王子神社", cat: "観光", lat: 34.3643, lng: 139.2446,
        url: "https://www.t-treasureislands.metro.tokyo.lg.jp/spotlist/niijima/455393-daisan-oji-jinja-shrine.html",
        note: "大三山山頂に鎮座。連なる鳥居の参道と港の眺望" },
      { name: "十三社神社", cat: "観光", lat: 34.3805, lng: 139.2579,
        url: "http://www.tokyo-jinjacho.or.jp/tosho/5309/",
        note: "伊豆諸島最大の神社。新島の総鎮守、獅子木遣は都無形文化財" },
      { name: "新島ガラスアートセンター", cat: "観光", lat: 34.362, lng: 139.2437,
        url: "https://www.niijimaglass.org/",
        note: "コーガ石から生まれるオリーブ色の新島ガラス。制作体験可" },
      { name: "新島村博物館", cat: "観光", lat: 34.3815, lng: 139.2592,
        url: "",
        note: "島の歴史・民俗・流人文化を紹介する村立博物館" },
      { name: "モヤイ像（湯の浜の丘）", cat: "観光", lat: 34.3648, lng: 139.2429,
        url: "https://niijima.or.jp/shokokai/niijima_moyai/",
        note: "渋谷モヤイ像のルーツ。コーガ石の石像が島内に多数点在" },
      { name: "栄寿司", cat: "食事・店", lat: 34.3728, lng: 139.2545,
        url: "https://niijima-info.jp/shop/3066/",
        note: "行列必至の島寿司の名店。地魚のヅケ握りが絶品" },
      { name: "かじやベーカリー", cat: "食事・店", lat: 34.3768, lng: 139.2548,
        url: "https://niijima-info.jp/shop/2971/",
        note: "朝7時開店、地元御用達の老舗パン屋。総菜パンが評判" },
      { name: "新島港（黒根港）", cat: "港・交通", lat: 34.3673, lng: 139.2444,
        url: "",
        note: "東海汽船の大型客船・ジェット船が発着する島の玄関口" },
      { name: "新島空港", cat: "港・交通", lat: 34.3695, lng: 139.2683,
        url: "",
        note: "調布飛行場から新中央航空で約40分。島の空の玄関" }
    ],
    shops: [],
    knowledge: [
          "コーガ石（抗火石）は世界でも新島とイタリアでしか採れない",
          "羽伏浦海岸は東洋一とも言われる白砂のビーチ"
    ],
    tips: [
          "湯の浜露天温泉は24時間無料・水着着用",
          "夏は本村のキャンプ場が便利、買い出しは本村で済ませる"
    ],
    logs: []
  },

  {
    id: "shikinejima", name: "式根島", region: "伊豆諸島", pref: "東京都",
    lat: 34.32, lng: 139.21,
    firstVisit: "2004", visits: 3, fav: true,
    summary: "新島の隣。入り組んだ海岸線と無料の海中温泉。すべてはここから始まった。",
    photos: [],
    spots: [
      { name: "大浦キャンプ場", cat: "キャンプ場", lat: 34.3295, lng: 139.2083,
        url: "https://shikinejima.tokyo/stay/camparea/1385/",
        note: "大浦海水浴場を見下ろす無料キャンプ場（約50張・要申請）。近年休業が続くため開設状況を要確認" },
      { name: "釜の下キャンプ場", cat: "キャンプ場", lat: 34.3229, lng: 139.2204,
        url: "https://shikinejima.tokyo/stay/camparea/1374/",
        note: "石白川海水浴場隣の無料キャンプ場（約30張・要申請）。温泉・商店に近い。開設状況を要確認" },
      { name: "泊海水浴場", cat: "ビーチ", lat: 34.3361, lng: 139.2114,
        url: "",
        note: "扇形の入り江に白砂。波静かで透明度が高い島随一の浜" },
      { name: "大浦海水浴場", cat: "ビーチ", lat: 34.3299, lng: 139.2079,
        url: "",
        note: "キャンプ場下の入り江。岩場に囲まれ磯遊びも" },
      { name: "中の浦海水浴場", cat: "ビーチ", lat: 34.3279, lng: 139.2061,
        url: "",
        note: "熱帯魚が多くシュノーケルの好ポイント" },
      { name: "石白川海水浴場", cat: "ビーチ", lat: 34.3235, lng: 139.2222,
        url: "",
        note: "集落から一番近い浜。夏は海の家も" },
      { name: "地鉈温泉", cat: "温泉", lat: 34.3179, lng: 139.216,
        url: "",
        note: "地面を鉈で割ったような谷底の海中温泉。無料・24時間、干潮前後が適温" },
      { name: "足付温泉", cat: "温泉", lat: 34.3199, lng: 139.2176,
        url: "",
        note: "岩場の無料海中温泉。外傷に効くと言われる「外科の湯」" },
      { name: "松が下雅湯", cat: "温泉", lat: 34.3206, lng: 139.2182,
        url: "",
        note: "水着で入る無料温泉。足湯併設・24時間" },
      { name: "式根島温泉 憩の家", cat: "温泉", lat: 34.3214, lng: 139.2164,
        url: "",
        note: "内湯の村営温泉。真水で流せるのはここだけ" },
      { name: "神引展望台", cat: "山・自然", lat: 34.3259, lng: 139.2039,
        url: "",
        note: "新東京百景。入り組んだ神引湾と伊豆諸島を一望する島一番の景観" },
      { name: "御釜湾第一展望台", cat: "山・自然", lat: 34.3207, lng: 139.202,
        url: "",
        note: "断崖の入り江・御釜湾を見下ろす" },
      { name: "まいまいず井戸", cat: "観光", lat: 34.3237, lng: 139.2201,
        url: "",
        note: "らせん状に掘り下げた江戸期の井戸。都指定史跡" },
      { name: "高森灯台", cat: "観光", lat: 34.3324, lng: 139.2205,
        url: "",
        note: "個人が私財で建てた灯台として知られる島北部の小灯台" },
      { name: "島cafe", cat: "食事・店", lat: 34.3283, lng: 139.2153,
        url: "",
        note: "集落のカフェ。営業日は要確認" },
      { name: "野伏港", cat: "港・交通", lat: 34.3352, lng: 139.2137,
        url: "https://www.tokaikisen.co.jp/boarding/terminal/",
        note: "式根島の玄関口。大型船・ジェット船・にしき（新島連絡船）が発着" }
    ],
    shops: [],
    knowledge: [
      "無料の海中温泉（地鉈・足付・松が下雅湯）は24時間入れる。潮位で湯加減が変わる",
      "島は周囲約12km。レンタサイクルで一周できる"
    ],
    tips: [
      "キャンプ場は無料だが要申請。近年休業が続いており最新状況を村役場（式根島支所）に確認",
      "食料は品数の多い新島側で調達してから渡るのも手（連絡船にしきで25分）"
    ],
    logs: [
      { date: "2004", text: "初めての島キャンプ。すべてここから始まった。" }
    ]
  },

  {
    id: "kozushima", name: "神津島", region: "伊豆諸島", pref: "東京都",
    lat: 34.2, lng: 139.13,
    firstVisit: "2009", visits: 7, fav: false,
    summary: "天上山と天の川。星空保護区に認定された島。",
    photos: [],
    spots: [
      { name: "都立多幸湾公園ファミリーキャンプ場", cat: "キャンプ場", lat: 34.204, lng: 139.1547,
        url: "https://takoucamp.com/",
        note: "天上山麓・多幸湾そばの公設キャンプ場。島のキャンプ主要拠点で通年開園" },
      { name: "ジョイキャンプだいじんこ", cat: "キャンプ場", lat: 34.2161, lng: 139.1326,
        url: "https://www.daijinko.com/",
        note: "沢尻海岸そばの民営キャンプ場。バンガロー有、温泉至近。12〜3月休業" },
      { name: "天上山", cat: "山・自然", lat: 34.2196, lng: 139.1532,
        url: "https://kozushima.com/kanko/yama/198/",
        note: "標高572m、花の百名山。砂漠状の山頂台地と不動池の天空絶景" },
      { name: "赤崎遊歩道", cat: "ビーチ", lat: 34.2396, lng: 139.1379,
        url: "https://kozushima.com/kanko/umi/beach/240/",
        note: "入り江に架かる木製遊歩道。飛び込み台とシュノーケリングの名所" },
      { name: "前浜海岸", cat: "ビーチ", lat: 34.205, lng: 139.1335,
        url: "https://kozushima.com/kanko/umi/beach/292/",
        note: "港の南に続く約650mの白砂ビーチ。集落至近のメイン海水浴場" },
      { name: "沢尻海岸", cat: "ビーチ", lat: 34.2176, lng: 139.1339,
        url: "https://kozushima.com/kanko/umi/beach/9525/",
        note: "静かな入り江の白砂ビーチ。旧キャンプ場は2020年閉鎖" },
      { name: "多幸湾（丸島海岸）", cat: "ビーチ", lat: 34.2028, lng: 139.1555,
        url: "https://kozushima.com/kanko/umi/keikan-umi/9539/",
        note: "天上山の断崖を望む景勝の湾。遊泳禁止だが景観と湧水で人気" },
      { name: "千両池", cat: "山・自然", lat: 34.1897, lng: 139.1211,
        url: "https://www.gotokyo.org/jp/spot/751/index.html",
        note: "波の浸食でできた瓢箪形の入り江。岩場を登って行く秘境絶景" },
      { name: "ありま展望台", cat: "山・自然", lat: 34.1989, lng: 139.1243,
        url: "https://kozushima.com/kanko/umi/keikan-umi/301/",
        note: "前浜を一望。おたあジュリアを偲ぶ大十字架のモニュメント" },
      { name: "多幸湧水", cat: "山・自然", lat: 34.2036, lng: 139.1546,
        url: "https://kozushima.com/kanko/meisho/wakimizu/282/",
        note: "東京の名湧水57選。天上山に染みた雨水が湧く水汲み場" },
      { name: "神津島温泉保養センター", cat: "温泉", lat: 34.2208, lng: 139.1296,
        url: "https://kozushima.com/kanko/meisho/other/230/",
        note: "海辺の岩場を使った大露天風呂が名物。ナトリウム塩化物強塩泉" },
      { name: "物忌奈命神社", cat: "観光", lat: 34.2084, lng: 139.1346,
        url: "https://kozushima.com/kanko/meisho/jinja/209/",
        note: "延喜式の名神大社。島の開祖・物忌奈命を祀る古社" },
      { name: "よたね広場", cat: "観光", lat: 34.2048, lng: 139.1386,
        url: "https://kozushima.com/kanko/meisho/other/12088/",
        note: "星空保護区の島を代表する星空観賞スポット。観賞会も開催" },
      { name: "神津島村郷土資料館", cat: "観光", lat: 34.208, lng: 139.1357,
        url: "https://kozushima.com/kanko/meisho/other/249/",
        note: "島の歴史資料・民具・出土品を展示。港から徒歩15分" },
      { name: "よっちゃーれセンター", cat: "食事・店", lat: 34.2081, lng: 139.1323,
        url: "https://kozushima.com/shop/taberu/356/",
        note: "漁協女性部運営の鮮魚店兼食堂。名物キンメダイの煮魚定食" },
      { name: "神津島港（前浜港）", cat: "港・交通", lat: 34.2093, lng: 139.1285,
        url: "https://www.tokaikisen.co.jp/island/kozushima/",
        note: "島の玄関口。竹芝からジェット船・大型客船が発着" },
      { name: "神津島空港", cat: "港・交通", lat: 34.1894, lng: 139.134,
        url: "https://www.kouwan.metro.tokyo.lg.jp/rito/tmg-airport/kozushima",
        note: "調布飛行場から新中央航空で約45分、1日3便の空の玄関口" }
    ],
    shops: [],
    knowledge: [
          "2020年に日本初の「星空保護区」に認定",
          "天上山(572m)は数時間で登れて山頂は別世界"
    ],
    tips: [
          "多幸湾の三浦キャンプ場は海が目の前",
          "水が豊富な島。湧き水『多幸湧水』はそのまま飲める"
    ],
    logs: []
  },

  {
    id: "miyakejima", name: "三宅島", region: "伊豆諸島", pref: "東京都",
    lat: 34.08, lng: 139.53,
    firstVisit: "2010", visits: 1, fav: true,
    summary: "雄山がそびえる火山の島。2010年に訪問、2026年に再訪・キャンプ予定。",
    photos: [],
    spots: [
      { name: "大久保浜キャンプ場", cat: "キャンプ場", lat: 34.1219, lng: 139.5169,
        url: "https://www.miyakejima.gr.jp/stay/camp/",
        note: "大久保浜すぐの村営キャンプ場。4〜11月営業、予約は「なっぷ」から。美化協力金1,000円/人" },
      { name: "錆ヶ浜海水浴場", cat: "ビーチ", lat: 34.0712, lng: 139.4808,
        url: "https://www.miyakejima.gr.jp/play/",
        note: "阿古の黒砂ビーチ。島の代表的な海水浴場で夕日の名所" },
      { name: "三池浜", cat: "ビーチ", lat: 34.0849, lng: 139.5614,
        url: "",
        note: "三池港近くに広がる黒砂の海岸。ウミガメも訪れる" },
      { name: "長太郎池", cat: "ビーチ", lat: 34.0539, lng: 139.5387,
        url: "",
        note: "溶岩に囲まれた天然の大プール。磯遊び・シュノーケルに最適" },
      { name: "富賀浜", cat: "ビーチ", lat: 34.054, lng: 139.4819,
        url: "",
        note: "テーブルサンゴの群生で知られる島南西のダイビングスポット" },
      { name: "ふるさとの湯", cat: "温泉", lat: 34.0655, lng: 139.4832,
        url: "https://www.miyakejima.gr.jp/play/furusatonoyu/",
        note: "太平洋に沈む夕日を望む日帰り温泉。大人500円・水曜定休" },
      { name: "雄山", cat: "山・自然", lat: 34.0884, lng: 139.528,
        url: "",
        note: "標高775mの活火山。2000年噴火で全島避難。山頂部は規制あり、最新情報を確認" },
      { name: "大路池", cat: "山・自然", lat: 34.0555, lng: 139.5255,
        url: "",
        note: "約2500年前の火口湖。アカコッコなど野鳥の楽園で探鳥の聖地" },
      { name: "ひょうたん山", cat: "山・自然", lat: 34.1017, lng: 139.5621,
        url: "",
        note: "1940年噴火でひと晩でできた火口丘。火口縁を歩ける" },
      { name: "新鼻新山", cat: "山・自然", lat: 34.0471, lng: 139.4996,
        url: "",
        note: "1983年噴火で一夜にして出現した赤黒い火砕丘" },
      { name: "新澪池跡", cat: "山・自然", lat: 34.0507, lng: 139.5024,
        url: "",
        note: "1983年噴火の水蒸気爆発で干上がった旧火口湖の跡" },
      { name: "メガネ岩", cat: "山・自然", lat: 34.0738, lng: 139.4751,
        url: "",
        note: "溶岩海岸のアーチ状奇岩。1962年噴火前は眼鏡型に穴が二つ並んでいた" },
      { name: "七島展望台", cat: "観光", lat: 34.0692, lng: 139.5086,
        url: "",
        note: "伊豆諸島の島々を一望。晴れれば富士山まで見える" },
      { name: "椎取神社", cat: "観光", lat: 34.1074, lng: 139.5577,
        url: "",
        note: "2000年噴火の泥流で埋まった鳥居と社殿をそのまま保存" },
      { name: "火山体験遊歩道", cat: "観光", lat: 34.0797, lng: 139.4788,
        url: "",
        note: "1983年溶岩流に埋まった旧阿古集落の上を歩く遊歩道" },
      { name: "伊豆岬", cat: "観光", lat: 34.1127, lng: 139.4895,
        url: "",
        note: "白い無人灯台が立つ草原の岬。星空観察の名所" },
      { name: "サタドー岬", cat: "観光", lat: 34.0935, lng: 139.5663,
        url: "",
        note: "断崖にぽつんと灯台が立つ島東端の岬。釣りの好ポイント" },
      { name: "アカコッコ館", cat: "観光", lat: 34.0524, lng: 139.5266,
        url: "https://www.miyakejima.gr.jp/see/akakokkokan/",
        note: "三宅島自然ふれあいセンター。日本野鳥の会レンジャー常駐、大路池畔の観察拠点" },
      { name: "ふるさと味覚館 宙-SOLA-", cat: "食事・店", lat: 34.0738, lng: 139.478,
        url: "https://www.miyake-sola.com/",
        note: "ふるさとの湯隣の食事処。昼は日替わり定食、夜は島の魚の居酒屋。水曜定休" },
      { name: "三池港", cat: "港・交通", lat: 34.0798, lng: 139.5636,
        url: "https://www.tokaikisen.co.jp/boarding/terminal/",
        note: "島東側の玄関口。就航率が高い主力港" },
      { name: "錆ヶ浜港", cat: "港・交通", lat: 34.0684, lng: 139.4805,
        url: "https://www.tokaikisen.co.jp/boarding/terminal/",
        note: "阿古地区の港。風向きにより三池港・伊ヶ谷港と使い分け" },
      { name: "三宅島空港", cat: "港・交通", lat: 34.0722, lng: 139.5597,
        url: "https://www.kouwan.metro.tokyo.lg.jp/rito/tmg-airport/miyakejima",
        note: "調布飛行場から約50分。火山ガスの状況により欠航あり" }
    ],
    shops: [],
    knowledge: [
      "雄山（おやま・775m）は活火山。2000年噴火で全島避難、2005年に避難指示解除",
      "島を一周する都道212号は周囲約30km、車・原付で1〜2時間",
      "野鳥の宝庫。アカコッコ（国の天然記念物）など固有種が見られる"
    ],
    tips: [
      "竹芝桟橋から東海汽船の大型船で約6.5時間（夜行）。調布からの飛行機もある",
      "港は風向きで三池/錆ヶ浜/伊ヶ谷を使い分け。出航前に着岸港を要確認",
      "火山ガスに注意。雄山周辺は規制エリアあり、最新情報を確認"
    ],
    logs: [
      { date: "2010", text: "はじめて三宅島へ。雄山の火山島の迫力。" }
    ]
  },

  {
    id: "mikurajima", name: "御蔵島", region: "伊豆諸島", pref: "東京都",
    lat: 33.88, lng: 139.6,
    firstVisit: "2012", visits: 1, fav: false,
    summary: "三宅島の南。イルカと原生林の険しい島。2012年訪問。",
    photos: [],
    spots: [
      { name: "イルカウォッチング（御蔵島港発）", cat: "観光", lat: 33.8965, lng: 139.5875,
        url: "https://mikura-isle.com/ocean/",
        note: "野生のミナミハンドウイルカと泳げる国内屈指の海。宿・ガイドの予約制" },
      { name: "御山", cat: "山・自然", lat: 33.8744, lng: 139.6019,
        url: "https://mikura-isle.com/mountain/",
        note: "最高峰851m。要ガイドのトレッキングで山頂は360度の大展望" },
      { name: "御代ヶ池", cat: "山・自然", lat: 33.8629, lng: 139.6106,
        url: "https://mikura-isle.com/mountain/",
        note: "原生林に囲まれた神秘の池。新東京百景。要ガイド" },
      { name: "南郷の森（大ジイ）", cat: "山・自然", lat: 33.8664, lng: 139.6262,
        url: "https://mikura-isle.com/mountain/",
        note: "幹回り約14mの日本最大級のスダジイ。巨樹の森の島を象徴する一本" },
      { name: "白滝", cat: "山・自然", lat: 33.8731, lng: 139.5779,
        url: "",
        note: "島西斜面の滝。断崖から海へ注ぐ姿は海上からも見える" },
      { name: "鈴原湿原", cat: "山・自然", lat: 33.8815, lng: 139.6013,
        url: "https://mikura-isle.com/mountain/",
        note: "御山中腹に広がる湿原。要ガイドのコース" },
      { name: "稲根神社", cat: "観光", lat: 33.8946, lng: 139.5934,
        url: "",
        note: "里集落の鎮守。本殿は南部の原生林の中に鎮座する" },
      { name: "御蔵島観光資料館", cat: "観光", lat: 33.8968, lng: 139.5922,
        url: "https://mikura-isle.com/wp202303/info-2/museum/",
        note: "観光案内所併設。島の自然・ツゲ細工・イルカの資料展示" },
      { name: "ふくまる商店", cat: "食事・店", lat: 33.8969, lng: 139.5914,
        url: "",
        note: "里集落の商店。食料・日用品の調達はここが頼り" },
      { name: "美美庵", cat: "食事・店", lat: 33.8973, lng: 139.592,
        url: "",
        note: "里集落の手打ちそば処。営業日は要確認" },
      { name: "御蔵島港", cat: "港・交通", lat: 33.8957, lng: 139.5893,
        url: "https://mikura-isle.com/access/",
        note: "島唯一の港。海況次第で欠航・条件付き出航が多い" },
      { name: "御蔵島ヘリポート", cat: "港・交通", lat: 33.8978, lng: 139.5949,
        url: "",
        note: "東京愛らんどシャトルで八丈島と約25分。船欠航時の代替手段" }
    ],
    shops: [],
    knowledge: [
      "島内にキャンプ場はなく、キャンプ・野宿は禁止。宿泊は民宿のみ（要予約）",
      "多くの山・森はガイド同行が必要。村のルールを守って歩く",
      "周囲の海に野生イルカが定住。ドルフィンスイムは春〜秋"
    ],
    tips: [
      "竹芝から夜行大型船で約7.5時間。着岸率が低めなので予備日があると安心",
      "船が欠航しても八丈島からのヘリ（愛らんどシャトル）という手がある",
      "宿が決まらないと上陸しづらい島。まず宿を押さえる"
    ],
    logs: []
  },

  {
    id: "hachijojima", name: "八丈島", region: "伊豆諸島", pref: "東京都",
    lat: 33.11, lng: 139.79,
    firstVisit: "2011", visits: 5, fav: true,
    summary: "ひょうたん型の常春の島。八丈富士と地熱・温泉。",
    photos: [],
    spots: [
      { name: "底土野営場", cat: "キャンプ場", lat: 33.1267, lng: 139.8144,
        url: "https://www.hachijo.gr.jp/specials/sokodo-campsite/",
        note: "底土港徒歩5分・無料70サイト。海水浴場に隣接し設備充実" },
      { name: "八丈プラザ公園キャンプ・BBQ場", cat: "キャンプ場", lat: 33.1044, lng: 139.7939,
        url: "https://www.hachijo.gr.jp/specials/hachijoplazapark-campsite/",
        note: "大賀郷の無料キャンプ場。要予約。スーパーが近く緑豊かで静か" },
      { name: "底土海水浴場", cat: "ビーチ", lat: 33.1235, lng: 139.8165,
        url: "https://www.hachijo.gr.jp/specials/sokodo-beach/",
        note: "島唯一の砂浜ビーチ。八丈ブルーの海でウミガメと泳げることも" },
      { name: "乙千代ヶ浜", cat: "ビーチ", lat: 33.0656, lng: 139.7941,
        url: "https://www.hachijo.gr.jp/specials/otchogahama-beach/",
        note: "タイドプールが人気の海水浴場。夏は子供用プールも開設" },
      { name: "末吉温泉 みはらしの湯", cat: "温泉", lat: 33.0792, lng: 139.8511,
        url: "https://www.hachijo.gr.jp/hotspring/miharashi/",
        note: "太平洋を見渡す絶景露天風呂。夜は星空、冬はクジラが見えることも" },
      { name: "樫立向里温泉 ふれあいの湯", cat: "温泉", lat: 33.0758, lng: 139.7903,
        url: "https://www.hachijo.gr.jp/hotspring/fureai/",
        note: "樫立地区の島民憩いの湯。杉林を望む露天風呂が人気" },
      { name: "八丈富士", cat: "山・自然", lat: 33.139, lng: 139.7651,
        url: "https://www.gotokyo.org/jp/spot/460/index.html",
        note: "標高854m伊豆諸島最高峰。お鉢巡りと火口内の神秘的な森" },
      { name: "ふれあい牧場", cat: "山・自然", lat: 33.1308, lng: 139.7675,
        url: "https://www.japan47go.travel/ja/detail/3d4cab55-49b3-4da1-b073-ef6b8b6b1bbe",
        note: "八丈富士中腹の牧場。放牧牛と島を一望できる展望台" },
      { name: "裏見ヶ滝", cat: "山・自然", lat: 33.0651, lng: 139.8161,
        url: "https://www.hachijo.gr.jp/nakanogo/",
        note: "滝を裏側から眺められる名瀑。近くに無料の混浴温泉あり" },
      { name: "南原千畳敷", cat: "山・自然", lat: 33.1061, lng: 139.7542,
        url: "https://www.gotokyo.org/jp/spot/473/index.html",
        note: "八丈富士の溶岩が作った黒い岩海岸。夕日と星空の名所" },
      { name: "名古の展望台", cat: "山・自然", lat: 33.0783, lng: 139.8425,
        url: "https://www.gotokyo.org/jp/spot/459/index.html",
        note: "高さ約180mの断崖上から太平洋と洞輪沢港を望む絶景" },
      { name: "登龍峠展望台", cat: "山・自然", lat: 33.1138, lng: 139.8362,
        url: "https://www.gotokyo.org/jp/spot/758/index.html",
        note: "龍が天に登る様の峠道。八丈富士と底土港を一望※通行止め情報に注意" },
      { name: "大坂トンネル展望台", cat: "山・自然", lat: 33.0849, lng: 139.7839,
        url: "",
        note: "八丈小島と横間海岸を見下ろす夕日の名所" },
      { name: "八丈植物公園", cat: "観光", lat: 33.1115, lng: 139.7844,
        url: "https://www.tokyo-park.or.jp/park/hachijo/index.html",
        note: "亜熱帯植物の都立公園。キョン飼育と光るキノコ展示が名物" },
      { name: "大里の玉石垣", cat: "観光", lat: 33.0986, lng: 139.7818,
        url: "https://www.hachijo.gr.jp/okago/",
        note: "陣屋跡に残る丸い玉石の石垣。流人が築いた歴史散歩道" },
      { name: "八丈島郷土料理 梁山泊", cat: "食事・店", lat: 33.1206, lng: 139.803,
        url: "https://www.hachijo.gr.jp/restaurant/ryozanpaku/",
        note: "島寿司・くさや・明日葉料理の有名店。島寿司は要予約" },
      { name: "底土港", cat: "港・交通", lat: 33.1229, lng: 139.8168,
        url: "https://www.hachijo.gr.jp/access",
        note: "竹芝からの大型客船が発着する島の海の玄関口" },
      { name: "八重根港", cat: "港・交通", lat: 33.0996, lng: 139.7716,
        url: "https://www.hachijo.gr.jp/access",
        note: "底土欠航時に大型客船が発着する西側の港。ダイビング拠点" },
      { name: "八丈島空港", cat: "港・交通", lat: 33.1149, lng: 139.7846,
        url: "https://hachijoapo.net/",
        note: "羽田から約55分・ANA1日3往復の空の玄関口" },
      { name: "藍ヶ江港", cat: "港・交通", lat: 33.0597, lng: 139.8157,
        url: "https://www.hachijo.gr.jp/nakanogo/",
        note: "透明度抜群の青い入り江の漁港。夏は港内で泳げる" }
    ],
    shops: [
          {
                "name": "藍ヶ江の漁港食堂",
                "type": "食事",
                "note": "島寿司と明日葉の天ぷら"
          }
    ],
    knowledge: [
          "羽田から飛行機で約55分、伊豆諸島で最も南の有人定期便",
          "八丈富士(854m)のお鉢巡りは1周約1時間"
    ],
    tips: [
          "底土野営場は港に近く飛行機・船どちらでもアクセス良好",
          "ふれあいの湯など温泉が点在、レンタカー推奨"
    ],
    logs: []
  },

  {
    id: "aogashima", name: "青ヶ島", region: "伊豆諸島", pref: "東京都",
    lat: 32.457, lng: 139.766,
    firstVisit: "", visits: 0, fav: false,
    summary: "二重カルデラの絶海の孤島。日本一人口の少ない村。",
    photos: [],
    spots: [
      { name: "大凸部", cat: "山・自然", lat: 32.4584, lng: 139.7593,
        url: "",
        note: "標高423mの島の最高点。二重カルデラの全景を見下ろす" },
      { name: "丸山（内輪山）", cat: "山・自然", lat: 32.4532, lng: 139.7665,
        url: "",
        note: "カルデラ内の火砕丘。お鉢巡りの遊歩道が一周できる" },
      { name: "ひんぎゃの地熱釜", cat: "観光", lat: 32.4535, lng: 139.765,
        url: "",
        note: "噴気孔（ひんぎゃ）の蒸気で卵や芋を蒸せる天然の釜" },
      { name: "青ヶ島村ふれあいサウナ", cat: "温泉", lat: 32.4526, lng: 139.7646,
        url: "",
        note: "地熱蒸気の村営サウナ。営業日は要確認" },
      { name: "神子の浦展望広場", cat: "観光", lat: 32.4694, lng: 139.7617,
        url: "",
        note: "外輪山の縁から断崖と海を見下ろす" },
      { name: "還住像", cat: "観光", lat: 32.4659, lng: 139.7631,
        url: "",
        note: "天明の大噴火の全島避難から約50年かけて帰島した「還住」の記念像" },
      { name: "三宝港", cat: "港・交通", lat: 32.4476, lng: 139.7589,
        url: "",
        note: "八丈島からの連絡船が発着。就航率が低く断崖にへばりつく特異な港" }
    ],
    shops: [],
    knowledge: [
      "人口約160人・日本で一番人口の少ない村。世界的にも珍しい二重式カルデラ",
      "アクセスは八丈島から連絡船（就航率5〜6割）またはヘリ（9席）のみ"
    ],
    tips: [
      "ヘリは予約困難・船は欠航前提。帰れない日を見込んで日程に余裕を",
      "キャンプは村営キャンプ場のみ可（事前に村役場へ申請）"
    ],
    logs: []
  },

  {
    id: "yakushima", name: "屋久島", region: "鹿児島の島", pref: "鹿児島県",
    lat: 30.34, lng: 130.51,
    firstVisit: "2013", visits: 4, fav: true,
    summary: "縄文杉と苔の森。月のうち35日雨が降ると言われる。",
    photos: [],
    spots: [
      { name: "屋久島青少年旅行村", cat: "キャンプ場", lat: 30.2712, lng: 130.4158,
        url: "https://www.town.yakushima.kagoshima.jp/cust-facility/1431/",
        note: "栗生の浜辺の町営キャンプ場。バンガロー有、カヌー体験も" },
      { name: "屋久島オーシャンビューキャンプ場", cat: "キャンプ場", lat: 30.4232, lng: 130.5808,
        url: "https://yakukan.jp/spot/7024.html",
        note: "宮之浦の高台にある海辺キャンプ場。釣り・星空観察に好適" },
      { name: "屋久島キャンピングパーク", cat: "キャンプ場", lat: 30.4415, lng: 130.5446,
        url: "https://www.yakushima-camping.com/",
        note: "宮之浦港から3.5km、磯海岸前の手作りキャンプ場" },
      { name: "癒しの体験型キャンプ場（永田いなか浜）", cat: "キャンプ場", lat: 30.4076, lng: 130.4349,
        url: "http://nagata-umigame.com/%E7%99%92%E3%81%97%E3%81%AE%E4%BD%93%E9%A8%93%E5%9E%8B%E3%82%AD%E3%83%A3%E3%83%B3%E3%83%97%E5%A0%B4/",
        note: "いなか浜前の体験型キャンプ場。4〜10月営業、バンガロー有" },
      { name: "永田いなか浜", cat: "ビーチ", lat: 30.4085, lng: 130.4339,
        url: "https://yakukan.jp/spot/7002.html",
        note: "日本一のアカウミガメ産卵地。ラムサール登録の800m砂浜" },
      { name: "平内海中温泉", cat: "温泉", lat: 30.231, lng: 130.4839,
        url: "https://yakukan.jp/spot/7015.html",
        note: "干潮前後2時間だけ入れる海中の野趣あふれる温泉" },
      { name: "湯泊温泉", cat: "温泉", lat: 30.2342, lng: 130.4777,
        url: "https://yakukan.jp/spot/7016.html",
        note: "海辺の露天風呂に24時間入浴可。協力金300円の秘湯" },
      { name: "尾之間温泉", cat: "温泉", lat: 30.2405, lng: 130.5486,
        url: "https://yakukan.jp/spot/7013.html",
        note: "モッチョム岳麓、地元の共同浴場。熱めの硫黄泉300円" },
      { name: "縄文杉", cat: "山・自然", lat: 30.3608, lng: 130.5319,
        url: "https://yakukan.jp/spot/7006.html",
        note: "推定樹齢数千年、屋久島最大級の屋久杉。往復約10時間" },
      { name: "ウィルソン株", cat: "山・自然", lat: 30.3566, lng: 130.5417,
        url: "https://yakukan.jp/spot/7007.html",
        note: "内部から見上げるとハート型。縄文杉ルートの人気地点" },
      { name: "白谷雲水峡", cat: "山・自然", lat: 30.38, lng: 130.5742,
        url: "https://yakukan.jp/spot/6985.html",
        note: "「もののけ姫」の苔むす森。太鼓岩からの絶景も人気" },
      { name: "ヤクスギランド", cat: "山・自然", lat: 30.3048, lng: 130.5754,
        url: "https://yakukan.jp/spot/6986.html",
        note: "標高1000mの自然休養林。屋久杉の巨木群を気軽に散策" },
      { name: "紀元杉", cat: "山・自然", lat: 30.3027, lng: 130.5455,
        url: "https://yakukan.jp/spot/6931.html",
        note: "推定樹齢3000年。車道脇から見られる屋久杉の巨木" },
      { name: "千尋の滝", cat: "山・自然", lat: 30.2625, lng: 130.5819,
        url: "https://yakukan.jp/spot/7001.html",
        note: "巨大な花崗岩の一枚岩を流れ落ちる落差約60mの滝" },
      { name: "トローキの滝", cat: "山・自然", lat: 30.2507, lng: 130.5906,
        url: "https://yakukan.jp/spot/7000.html",
        note: "海に直接落ちる珍しい滝。ぽん・たん館から徒歩5分" },
      { name: "大川の滝", cat: "山・自然", lat: 30.2996, lng: 130.4135,
        url: "https://yakukan.jp/spot/6999.html",
        note: "落差88mで島最大。日本の滝100選の豪快な滝" },
      { name: "西部林道", cat: "山・自然", lat: 30.3578, lng: 130.3979,
        url: "https://yakukan.jp/spot/7003.html",
        note: "世界遺産区域を通る唯一の車道。ヤクシカ・ヤクザルに遭遇" },
      { name: "屋久島灯台", cat: "観光", lat: 30.3922, lng: 130.3797,
        url: "https://yakukan.jp/spot/7004.html",
        note: "明治30年築、永田岬に立つ白亜の灯台。夕日の名所" },
      { name: "屋久どん", cat: "食事・店", lat: 30.3203, lng: 130.6607,
        url: "",
        note: "安房港近くの名物店。トビウオ料理と屋久どんが看板" },
      { name: "宮之浦港", cat: "港・交通", lat: 30.4324, lng: 130.5724,
        url: "https://yakukan.jp/to-island.html",
        note: "島最大の玄関口。鹿児島からフェリー・高速船が発着" },
      { name: "安房港", cat: "港・交通", lat: 30.3173, lng: 130.6589,
        url: "https://yakukan.jp/to-island.html",
        note: "高速船トッピー・ロケットが発着。縄文杉登山口に近い" },
      { name: "屋久島空港", cat: "港・交通", lat: 30.3856, lng: 130.6592,
        url: "https://yakukan.jp/to-island.html",
        note: "鹿児島・福岡・大阪から直行便が就航する空の玄関口" }
    ],
    shops: [],
    knowledge: [
          "世界自然遺産。標高2000m近い山が海から立ち上がる",
          "白谷雲水峡は『もののけ姫』の森のモデルとされる"
    ],
    tips: [
          "縄文杉は往復20km・10時間級、早朝出発が必須",
          "雨具は上下セパレートの本格的なものを。樹皮の苔は雨で輝く"
    ],
    logs: []
  },

  {
    id: "tanegashima", name: "種子島", region: "鹿児島の島", pref: "鹿児島県",
    lat: 30.60, lng: 130.95,
    firstVisit: "", visits: 0, fav: false,
    summary: "鉄砲伝来とロケット発射場。南北に長い平らな島。",
    photos: [],
    spots: [
      { name: "種子島宇宙センター", cat: "観光", lat: 30.3777, lng: 130.9577,
        url: "https://fanfun.jaxa.jp/visit/tanegashima/",
        note: "日本最大のロケット発射場。「世界一美しい発射場」と称される" },
      { name: "宇宙科学技術館", cat: "観光", lat: 30.3749, lng: 130.9577,
        url: "",
        note: "宇宙センター内の展示館。見学無料、施設ツアーも" },
      { name: "千座の岩屋", cat: "山・自然", lat: 30.4475, lng: 130.9722,
        url: "",
        note: "千人座れると言われる海食洞窟。干潮時のみ中に入れる" },
      { name: "浦田海水浴場", cat: "ビーチ", lat: 30.8221, lng: 131.0389,
        url: "",
        note: "島北端の入り江。快水浴場百選の遠浅ビーチ" },
      { name: "熊野海水浴場", cat: "ビーチ", lat: 30.4587, lng: 130.9596,
        url: "",
        note: "東海岸の白砂ビーチ。隣接してキャンプ場がある" },
      { name: "種子島自然レクリエーション村", cat: "キャンプ場", lat: 30.4583, lng: 130.9585,
        url: "",
        note: "熊野海水浴場そばの公営キャンプ場。バンガローもあり" },
      { name: "天女ヶ倉", cat: "山・自然", lat: 30.7436, lng: 131.0533,
        url: "",
        note: "巨岩が重なる標高238mの展望所。東シナ海と太平洋を見渡す" },
      { name: "たねがしま赤米館", cat: "観光", lat: 30.3846, lng: 130.935,
        url: "",
        note: "宝満神社に伝わる赤米の資料館" },
      { name: "西之表港", cat: "港・交通", lat: 30.7314, lng: 130.9898,
        url: "",
        note: "鹿児島からの高速船・フェリーが発着する島の玄関口" },
      { name: "種子島空港", cat: "港・交通", lat: 30.6046, lng: 130.9916,
        url: "",
        note: "島中央部。鹿児島空港から約40分" }
    ],
    shops: [],
    knowledge: [
      "1543年鉄砲伝来の島。南北約58kmと細長く移動距離が長い",
      "ロケット打上げ日は宇宙センター周辺に見学規制がかかる"
    ],
    tips: [
      "打上げ見学は事前に射点からの距離と見学場所を確認",
      "レンタカー推奨。安納芋のスイーツはシーズン限定"
    ],
    logs: []
  },

  {
    id: "amami-oshima", name: "奄美大島", region: "鹿児島の島", pref: "鹿児島県",
    lat: 28.37, lng: 129.49,
    firstVisit: "2015", visits: 3, fav: false,
    summary: "マングローブと金作原の原生林。鶏飯と黒糖焼酎。",
    photos: [],
    spots: [
      { name: "小浜キャンプ場（大浜海浜公園）", cat: "キャンプ場", lat: 28.4037, lng: 129.4551,
        url: "https://www.ohama.marutani-amami.com/kohama-camp",
        note: "大浜海浜公園内。名瀬市街に近い通年営業の海辺キャンプ場" },
      { name: "ヤドリ浜キャンプ場", cat: "キャンプ場", lat: 28.1255, lng: 129.3626,
        url: "https://www.kagoshima-kankou.com/guide/10245",
        note: "島南部・大島海峡入口の無料キャンプ場。白砂ビーチ隣接" },
      { name: "奄美フォレストポリスキャンプ場", cat: "キャンプ場", lat: 28.3171, lng: 129.3349,
        url: "http://www.amamiforest.com/",
        note: "湯湾岳麓の森林公園内。バンガロー充実、マテリヤの滝至近" },
      { name: "奄美リゾートばしゃ山村 キャンプ場", cat: "キャンプ場", lat: 28.4034, lng: 129.6483,
        url: "http://basyayama-mura.com/",
        note: "用安海岸ビーチ前。リゾートホテル併設のキャンプサイト" },
      { name: "西古見GATE", cat: "キャンプ場", lat: 28.2424, lng: 129.1754,
        url: "https://nishikomigate.com/",
        note: "最西端集落の町営キャンプ場。サウナ付浴場と満天の星空" },
      { name: "マングローブ茶屋", cat: "キャンプ場", lat: 28.2573, lng: 129.4084,
        url: "https://mangroveamami.com/",
        note: "マングローブ林前の老舗テント村。カヌー体験と鶏飯丼が人気" },
      { name: "土盛海岸", cat: "ビーチ", lat: 28.4655, lng: 129.717,
        url: "https://www.kagoshima-kankou.com/guide/10224",
        note: "通称ブルーエンジェル。空港近くの白砂とコバルトブルーの海" },
      { name: "大浜海浜公園", cat: "ビーチ", lat: 28.4031, lng: 129.456,
        url: "https://www.ohama.marutani-amami.com/",
        note: "夕陽の名所。園内に奄美海洋展示館と小浜キャンプ場" },
      { name: "THE SCENE 天然温泉きゅらの湯", cat: "温泉", lat: 28.1261, lng: 129.3618,
        url: "https://hotelthescene.com/",
        note: "奄美大島唯一の天然温泉。島南端リゾートホテルの露天風呂" },
      { name: "金作原原生林", cat: "山・自然", lat: 28.3419, lng: 129.4466,
        url: "https://www.kagoshima-kankou.com/guide/10199",
        note: "ヒカゲヘゴ茂る亜熱帯の原生林。認定ガイド同行が必須" },
      { name: "黒潮の森マングローブパーク", cat: "山・自然", lat: 28.2593, lng: 129.409,
        url: "https://www.mangrovepark.com/",
        note: "国内有数のマングローブ林。カヌー探検が人気。道の駅併設" },
      { name: "あやまる岬観光公園", cat: "山・自然", lat: 28.4734, lng: 129.7174,
        url: "https://www.kagoshima-kankou.com/guide/10223",
        note: "奄美十景の岬。展望台と天然の海中プール、島北端の絶景" },
      { name: "マテリヤの滝", cat: "山・自然", lat: 28.3168, lng: 129.3512,
        url: "https://amami.org/sightseeing/materia",
        note: "名は「本当に美しい太陽の滝壺」の意。森の中の神秘の滝" },
      { name: "ホノホシ海岸", cat: "山・自然", lat: 28.1307, lng: 129.3713,
        url: "https://www.kagoshima-kankou.com/guide/10244",
        note: "荒波が磨いた玉石が鳴る海岸。玉石の持ち出しは禁止" },
      { name: "ハートロック", cat: "山・自然", lat: 28.4068, lng: 129.6285,
        url: "https://www.town.tatsugo.lg.jp/kikakukanko/kanko/heartrock.html",
        note: "干潮時のみ現れるハート形の潮だまり。恋愛パワースポット" },
      { name: "奄美パーク・田中一村記念美術館", cat: "観光", lat: 28.418, lng: 129.6942,
        url: "https://amamipark.com/",
        note: "奄美の自然・文化紹介施設。田中一村の作品約80点を展示" },
      { name: "けいはん ひさ倉", cat: "食事・店", lat: 28.4147, lng: 129.6009,
        url: "https://www.town.tatsugo.lg.jp/kikakukanko/shisetsu/taberu/06.html",
        note: "郷土料理・鶏飯の代表格。自家養鶏の地鶏と黄金スープ" },
      { name: "奄美空港", cat: "港・交通", lat: 28.4309, lng: 129.7103,
        url: "https://amami-airport.co.jp/",
        note: "島の空の玄関口。東京・大阪・鹿児島などから直行便" },
      { name: "名瀬港", cat: "港・交通", lat: 28.3897, lng: 129.495,
        url: "",
        note: "鹿児島・沖縄航路のフェリーが発着する海の玄関口" }
    ],
    shops: [
          {
                "name": "鶏飯の老舗",
                "type": "食事",
                "note": "ご飯に具をのせ鶏スープをかける郷土料理"
          }
    ],
    knowledge: [
          "2021年に世界自然遺産に登録",
          "アマミノクロウサギなど固有種の宝庫"
    ],
    tips: [
          "住用川のマングローブはカヌーで漕ぎ進める",
          "ハブに注意。藪や夜間の移動は気をつける"
    ],
    logs: []
  },

  {
    id: "kikaijima", name: "喜界島", region: "鹿児島の島", pref: "鹿児島県",
    lat: 28.32, lng: 129.94,
    firstVisit: "2017", visits: 1, fav: false,
    summary: "隆起サンゴ礁の平らな島。サトウキビと白ゴマ。2017年訪問。",
    photos: [],
    spots: [
      { name: "スギラビーチ", cat: "ビーチ", lat: 28.3205, lng: 129.9217,
        url: "",
        note: "空港そばの遠浅ビーチ。防波堤に囲まれ子どもでも安心" },
      { name: "ハワイビーチ", cat: "ビーチ", lat: 28.3773, lng: 130.0157,
        url: "",
        note: "小野津集落近くの天然プール。岩礁に囲まれた透明な海" },
      { name: "百之台展望所", cat: "山・自然", lat: 28.3191, lng: 129.9854,
        url: "",
        note: "隆起サンゴ礁の台地・百之台の展望所。国立公園" },
      { name: "ウフヤグチ鍾乳洞", cat: "山・自然", lat: 28.3208, lng: 129.9705,
        url: "",
        note: "入口が大きく開いた鍾乳洞。自由に見学できる" },
      { name: "手久津久のガジュマル巨木", cat: "山・自然", lat: 28.2919, lng: 129.9355,
        url: "",
        note: "集落の中の巨大ガジュマル。気根が林のように広がる" },
      { name: "サトウキビの一本道", cat: "観光", lat: 28.3429, lng: 129.993,
        url: "",
        note: "キビ畑の中を約3.5km直進する撮影名所" },
      { name: "阿伝集落のサンゴの石垣", cat: "観光", lat: 28.365, lng: 130.0002,
        url: "",
        note: "サンゴを積んだ石垣が続く昔ながらの集落" },
      { name: "荒木海岸展望台（さんご苑）", cat: "観光", lat: 28.3092, lng: 129.9148,
        url: "",
        note: "東シナ海に沈む夕日の名所" },
      { name: "サンゴcafe", cat: "食事・店", lat: 28.338, lng: 130.0033,
        url: "",
        note: "早町港近くのカフェ。営業日は要確認" },
      { name: "湾港", cat: "港・交通", lat: 28.3264, lng: 129.9371,
        url: "",
        note: "鹿児島・奄美からのフェリーが発着" },
      { name: "喜界空港", cat: "港・交通", lat: 28.3216, lng: 129.9279,
        url: "",
        note: "鹿児島・奄美大島からの小型機が発着" }
    ],
    shops: [],
    knowledge: [
      "今も年約2mmずつ隆起し続けるサンゴ礁の島。白ゴマの生産量日本一",
      "起伏が少なく自転車・バイクで回りやすい"
    ],
    tips: [
      "レンタバイクで一周約2時間。ガソリンスタンドは集落部のみ"
    ],
    logs: []
  },

  {
    id: "tokunoshima", name: "徳之島", region: "鹿児島の島", pref: "鹿児島県",
    lat: 27.80, lng: 128.93,
    firstVisit: "2018", visits: 1, fav: false,
    summary: "闘牛とトライアスロンの島。世界自然遺産。2018年訪問。",
    photos: [],
    spots: [
      { name: "畦プリンスビーチ", cat: "ビーチ", lat: 27.8493, lng: 128.9712,
        url: "",
        note: "皇太子夫妻（当時）が訪れた遠浅の白砂ビーチ。海浜公園" },
      { name: "畦キャンプ場", cat: "キャンプ場", lat: 27.8463, lng: 128.9698,
        url: "",
        note: "畦プリンスビーチに隣接するキャンプ場" },
      { name: "金見崎展望所", cat: "山・自然", lat: 27.8905, lng: 128.968,
        url: "",
        note: "ソテツトンネルを抜けた先の展望所。トンバラ岩を望む" },
      { name: "ムシロ瀬", cat: "山・自然", lat: 27.8935, lng: 128.9011,
        url: "",
        note: "花崗岩がムシロを敷いたように広がる奇観の海岸" },
      { name: "犬の門蓋", cat: "山・自然", lat: 27.8071, lng: 128.8875,
        url: "",
        note: "断崖と奇岩群。夕日に浮かぶメガネ岩が有名" },
      { name: "ウンブキ（陸の中の海）", cat: "山・自然", lat: 27.8274, lng: 128.8835,
        url: "",
        note: "陸の洞窟に海がつながる天然水中鍾乳洞" },
      { name: "徳之島世界遺産センター", cat: "観光", lat: 27.8268, lng: 128.9544,
        url: "",
        note: "世界自然遺産・徳之島の自然を学べる拠点施設" },
      { name: "花徳闘牛場", cat: "観光", lat: 27.8208, lng: 128.9654,
        url: "",
        note: "島の闘牛文化の会場のひとつ。大会日程は要確認" },
      { name: "亀徳港", cat: "港・交通", lat: 27.7378, lng: 129.0243,
        url: "",
        note: "鹿児島〜沖縄航路のフェリーが発着する玄関口" },
      { name: "平土野港", cat: "港・交通", lat: 27.8123, lng: 128.8916,
        url: "",
        note: "西岸の港。奄美海運のフェリーが発着" },
      { name: "徳之島子宝空港", cat: "港・交通", lat: 27.8354, lng: 128.8821,
        url: "",
        note: "鹿児島・奄美からの便が発着" }
    ],
    shops: [],
    knowledge: [
      "2021年に奄美大島・沖縄北部などとともに世界自然遺産登録",
      "闘牛は牛同士を戦わせる島の伝統行事。全島大会は年3回"
    ],
    tips: [
      "見どころが島の外周に散らばる。レンタカーで一周約3時間"
    ],
    logs: []
  },

  {
    id: "okinoerabu", name: "沖永良部島", region: "鹿児島の島", pref: "鹿児島県",
    lat: 27.37, lng: 128.57,
    firstVisit: "", visits: 0, fav: false,
    summary: "隆起サンゴ礁の花の島。鍾乳洞とケイビング。",
    photos: [],
    spots: [
      { name: "ワンジョビーチ", cat: "ビーチ", lat: 27.4098, lng: 128.6349,
        url: "",
        note: "松林に縁どられた白砂のロングビーチ" },
      { name: "ウジジ浜", cat: "ビーチ", lat: 27.3433, lng: 128.6013,
        url: "",
        note: "奇岩群から昇る朝日の名所" },
      { name: "沖泊海浜公園", cat: "ビーチ", lat: 27.3951, lng: 128.5588,
        url: "",
        note: "断崖に挟まれた入り江の海浜公園。キャンプも可" },
      { name: "大山野営場", cat: "キャンプ場", lat: 27.3639, lng: 128.5748,
        url: "",
        note: "島最高部・大山の森のキャンプ場" },
      { name: "昇竜洞", cat: "山・自然", lat: 27.3626, lng: 128.5525,
        url: "",
        note: "全長3.5kmの鍾乳洞（公開600m）。フローストーンが見事" },
      { name: "フーチャ", cat: "山・自然", lat: 27.4376, lng: 128.6871,
        url: "",
        note: "波が吹き上げる潮吹き洞窟。荒天時は数十mの潮柱" },
      { name: "大山植物公園展望台", cat: "山・自然", lat: 27.3615, lng: 128.5712,
        url: "",
        note: "標高240mから島全体とサンゴ礁の海を一望" },
      { name: "ジッキョヌホー", cat: "観光", lat: 27.3377, lng: 128.5801,
        url: "",
        note: "平成の名水百選の湧水。集落の洗い場が残る" },
      { name: "世之主の墓", cat: "観光", lat: 27.3834, lng: 128.6121,
        url: "",
        note: "島北部に残る琉球式の大型墳墓" },
      { name: "西郷南洲記念館", cat: "観光", lat: 27.3956, lng: 128.6566,
        url: "",
        note: "西郷隆盛が流罪で1年半を過ごした地の記念館" },
      { name: "和泊港", cat: "港・交通", lat: 27.3983, lng: 128.6656,
        url: "",
        note: "鹿児島〜沖縄航路のフェリーが発着" },
      { name: "沖永良部空港", cat: "港・交通", lat: 27.4315, lng: 128.7051,
        url: "",
        note: "鹿児島・奄美・沖縄からの便が発着" }
    ],
    shops: [],
    knowledge: [
      "島内に200以上の鍾乳洞。ガイド付きケイビングツアーが名物",
      "えらぶゆりとフリージアの花の島。春は花畑が広がる"
    ],
    tips: [
      "昇竜洞と大山はセットで回りやすい。洞内は年間を通して涼しい"
    ],
    logs: []
  },

  {
    id: "yoron", name: "与論島", region: "鹿児島の島", pref: "鹿児島県",
    lat: 27.04, lng: 128.42,
    firstVisit: "", visits: 0, fav: false,
    summary: "百合ヶ浜の白砂。鹿児島最南端、沖縄のすぐ北。",
    photos: [],
    spots: [
      { name: "百合ヶ浜", cat: "ビーチ", lat: 27.0389, lng: 128.4655,
        url: "",
        note: "大潮の干潮時だけ沖に現れる幻の白砂の砂州。グラスボートで渡る" },
      { name: "大金久海岸", cat: "ビーチ", lat: 27.0391, lng: 128.454,
        url: "",
        note: "百合ヶ浜行きの船が出る約2kmの白砂海岸" },
      { name: "ウドノスビーチ", cat: "ビーチ", lat: 27.0521, lng: 128.4147,
        url: "",
        note: "夕日の名所。ウミガメに会えることも" },
      { name: "大金久キャンプ場", cat: "キャンプ場", lat: 27.0371, lng: 128.4527,
        url: "",
        note: "大金久海岸沿いのキャンプ場" },
      { name: "舵引きの丘", cat: "山・自然", lat: 27.0469, lng: 128.4281,
        url: "",
        note: "島北部の高台。サンゴ礁のリーフと海の色を一望" },
      { name: "サザンクロスセンター", cat: "観光", lat: 27.0287, lng: 128.4294,
        url: "",
        note: "琉球・奄美の歴史資料館。展望塔から百合ヶ浜方面を望む" },
      { name: "与論民俗村", cat: "観光", lat: 27.0251, lng: 128.4529,
        url: "",
        note: "島南部で伝統家屋と島の暮らしを伝える" },
      { name: "くじらカフェ", cat: "食事・店", lat: 27.0289, lng: 128.4165,
        url: "",
        note: "茶花集落近くのカフェ。営業日は要確認" },
      { name: "与論港", cat: "港・交通", lat: 27.0364, lng: 128.401,
        url: "",
        note: "鹿児島〜沖縄航路のフェリーが発着" },
      { name: "与論空港", cat: "港・交通", lat: 27.0438, lng: 128.4017,
        url: "",
        note: "鹿児島・奄美・那覇からの便が発着" }
    ],
    shops: [],
    knowledge: [
      "百合ヶ浜の出現は大潮の干潮前後のみ。月ごとの出現予想を要確認",
      "周囲約23kmの隆起サンゴ礁の島。ヨロン島は沖縄本島まで約23km"
    ],
    tips: [
      "百合ヶ浜ツアーは午前が多い。星の砂探しも人気"
    ],
    logs: []
  },

  {
    id: "okinawa-hontou", name: "沖縄本島", region: "沖縄の島", pref: "沖縄県",
    lat: 26.50, lng: 127.95,
    firstVisit: "", visits: 0, fav: false,
    summary: "沖縄の中心。首里城と美ら海。離島めぐりの拠点。",
    photos: [],
    spots: [
      { name: "沖縄美ら海水族館", cat: "観光", lat: 26.6944, lng: 127.8779,
        url: "https://churaumi.okinawa/",
        note: "ジンベエザメが泳ぐ大水槽「黒潮の海」。海洋博公園内" },
      { name: "首里城公園", cat: "観光", lat: 26.218, lng: 127.7162,
        url: "https://oki-park.jp/shurijo/",
        note: "琉球王国の王城。世界遺産（正殿は火災からの復元が進む）" },
      { name: "万座毛", cat: "山・自然", lat: 26.5041, lng: 127.8507,
        url: "",
        note: "「万人を座するに足る」象の鼻の断崖景勝地" },
      { name: "古宇利大橋", cat: "観光", lat: 26.6866, lng: 128.0173,
        url: "",
        note: "エメラルドの海を渡る約2kmの橋。古宇利島へ" },
      { name: "斎場御嶽", cat: "観光", lat: 26.1734, lng: 127.8274,
        url: "",
        note: "琉球王国最高の聖地。世界遺産" },
      { name: "辺戸岬", cat: "山・自然", lat: 26.872, lng: 128.2656,
        url: "",
        note: "本島最北端の断崖。晴れた日は与論島が見える" },
      { name: "真栄田岬（青の洞窟）", cat: "山・自然", lat: 26.4463, lng: 127.7714,
        url: "",
        note: "シュノーケル・ダイビングで人気の青の洞窟の入口" },
      { name: "今帰仁城跡", cat: "観光", lat: 26.691, lng: 127.9296,
        url: "",
        note: "世界遺産の城跡。1月の寒緋桜の名所" },
      { name: "ひめゆりの塔・平和祈念資料館", cat: "観光", lat: 26.0965, lng: 127.6903,
        url: "",
        note: "沖縄戦の看護学徒の慰霊碑と資料館" },
      { name: "平和祈念公園", cat: "観光", lat: 26.0965, lng: 127.7252,
        url: "",
        note: "沖縄戦終焉の地・摩文仁の丘の公園。平和の礎" },
      { name: "おきなわワールド（玉泉洞）", cat: "観光", lat: 26.1398, lng: 127.749,
        url: "",
        note: "全長5kmの鍾乳洞・玉泉洞とエイサー演舞のテーマパーク" },
      { name: "国際通り", cat: "観光", lat: 26.2138, lng: 127.6809,
        url: "",
        note: "那覇の目抜き通り約1.6km。奇跡の1マイル" },
      { name: "アメリカンビレッジ", cat: "観光", lat: 26.3165, lng: 127.7574,
        url: "",
        note: "北谷の海辺のタウンリゾート。観覧車とサンセット" },
      { name: "ムーンビーチ", cat: "ビーチ", lat: 26.451, lng: 127.8018,
        url: "",
        note: "恩納村の三日月形の天然ビーチ" },
      { name: "波の上ビーチ", cat: "ビーチ", lat: 26.2213, lng: 127.672,
        url: "",
        note: "那覇市街で唯一泳げるビーチ。波上宮の下" },
      { name: "比地大滝キャンプ場", cat: "キャンプ場", lat: 26.7189, lng: 128.1796,
        url: "",
        note: "やんばるの森・比地大滝トレッキングの起点キャンプ場" },
      { name: "泊港（とまりん）", cat: "港・交通", lat: 26.2241, lng: 127.6834,
        url: "",
        note: "慶良間・久米島など離島航路の拠点" },
      { name: "那覇空港", cat: "港・交通", lat: 26.1967, lng: 127.6443,
        url: "",
        note: "沖縄の空の玄関口。離島便の乗継拠点" }
    ],
    shops: [],
    knowledge: [
      "北部やんばるは世界自然遺産。南部は沖縄戦の戦跡が多い",
      "泊港（とまりん）と那覇空港が離島めぐりのハブ"
    ],
    tips: [
      "美ら海水族館と今帰仁城跡・古宇利島は北部セットで1日コース"
    ],
    logs: []
  },

  {
    id: "kumejima", name: "久米島", region: "沖縄の島", pref: "沖縄県",
    lat: 26.35, lng: 126.80,
    firstVisit: "", visits: 0, fav: false,
    summary: "はての浜の砂州と久米島紬。琉球一の美しさと讃えられた島。",
    photos: [],
    spots: [
      { name: "はての浜", cat: "ビーチ", lat: 26.3457, lng: 126.8854,
        url: "",
        note: "全長約7kmの真っ白な砂州の無人島。ツアー船で渡る" },
      { name: "イーフビーチ", cat: "ビーチ", lat: 26.3325, lng: 126.8113,
        url: "",
        note: "日本の渚百選。約2km続く遠浅の白砂" },
      { name: "シンリ浜", cat: "ビーチ", lat: 26.3557, lng: 126.718,
        url: "",
        note: "空港そばの夕日の名所" },
      { name: "シンリ浜キャンプ場", cat: "キャンプ場", lat: 26.3558, lng: 126.7167,
        url: "",
        note: "シンリ浜海浜公園のキャンプ場" },
      { name: "畳石", cat: "山・自然", lat: 26.3357, lng: 126.8253,
        url: "",
        note: "奥武島の亀甲状の溶岩。国指定天然記念物" },
      { name: "ミーフガー", cat: "山・自然", lat: 26.3869, lng: 126.7547,
        url: "",
        note: "穴の開いた巨岩「女岩」。子宝祈願の名所" },
      { name: "宇江城城跡", cat: "山・自然", lat: 26.3771, lng: 126.7701,
        url: "",
        note: "島最高所・標高310mの城跡。360度の大パノラマ" },
      { name: "五枝の松", cat: "山・自然", lat: 26.3587, lng: 126.7425,
        url: "",
        note: "地を這うように枝を広げる琉球松の巨木。国指定天然記念物" },
      { name: "上江洲家住宅", cat: "観光", lat: 26.355, lng: 126.7489,
        url: "",
        note: "琉球王朝時代の士族屋敷。国指定重要文化財" },
      { name: "久米島紬ゆいまーる館", cat: "観光", lat: 26.3555, lng: 126.806,
        url: "",
        note: "重要無形文化財・久米島紬の工房見学と展示" },
      { name: "兼城港", cat: "港・交通", lat: 26.3414, lng: 126.7532,
        url: "",
        note: "那覇（泊港）からのフェリーが発着" },
      { name: "久米島空港", cat: "港・交通", lat: 26.364, lng: 126.7143,
        url: "",
        note: "那覇から約35分。夏は羽田直行便も" }
    ],
    shops: [],
    knowledge: [
      "はての浜ツアーは半日〜1日。日差しを遮るものがないので日焼け対策必須",
      "車えびの養殖が日本一"
    ],
    tips: [
      "はての浜は午前便が海の色がきれい。島本体は1周約48km"
    ],
    logs: []
  },

  {
    id: "miyako", name: "宮古島", region: "沖縄の島", pref: "沖縄県",
    lat: 24.79, lng: 125.30,
    firstVisit: "", visits: 0, fav: false,
    summary: "宮古ブルーの海と前浜ビーチ。橋でつながる離島群。",
    photos: [],
    spots: [
      { name: "与那覇前浜ビーチ", cat: "ビーチ", lat: 24.736, lng: 125.263,
        url: "",
        note: "「東洋一」と称される約7kmの白砂。来間島を望む" },
      { name: "砂山ビーチ", cat: "ビーチ", lat: 24.8394, lng: 125.2806,
        url: "",
        note: "砂丘を越えた先に現れる岩のアーチのビーチ" },
      { name: "パイナガマビーチ", cat: "ビーチ", lat: 24.8029, lng: 125.2709,
        url: "",
        note: "市街地から徒歩圏の身近なビーチ" },
      { name: "新城海岸", cat: "ビーチ", lat: 24.7613, lng: 125.423,
        url: "",
        note: "遠浅のサンゴ礁でシュノーケルの定番。ウミガメも" },
      { name: "イムギャーマリンガーデン", cat: "ビーチ", lat: 24.7238, lng: 125.3572,
        url: "",
        note: "入り江の天然プール。初心者シュノーケルに最適" },
      { name: "東平安名崎", cat: "山・自然", lat: 24.7188, lng: 125.4691,
        url: "",
        note: "太平洋と東シナ海を分けて2km突き出す絶景の岬" },
      { name: "西平安名崎", cat: "山・自然", lat: 24.9102, lng: 125.2552,
        url: "",
        note: "島最北端。池間大橋と風車を望む" },
      { name: "島尻のマングローブ林", cat: "山・自然", lat: 24.8762, lng: 125.2902,
        url: "",
        note: "宮古島最大のマングローブ。遊歩道で観察できる" },
      { name: "伊良部大橋", cat: "観光", lat: 24.7967, lng: 125.2395,
        url: "",
        note: "無料で渡れる橋として日本最長の3540m。宮古ブルーの海の上" },
      { name: "池間大橋", cat: "観光", lat: 24.9157, lng: 125.2661,
        url: "",
        note: "池間島へ渡る1425m。橋上からの海の色が名物" },
      { name: "来間大橋", cat: "観光", lat: 24.7256, lng: 125.2641,
        url: "",
        note: "来間島へ渡る1690m。前浜ビーチを一望" },
      { name: "雪塩ミュージアム", cat: "観光", lat: 24.9022, lng: 125.2682,
        url: "",
        note: "宮古島の名産・雪塩の製塩所見学" },
      { name: "平良港", cat: "港・交通", lat: 24.8066, lng: 125.2745,
        url: "",
        note: "市街地の港。伊良部・多良間航路の歴史をもつ拠点港" },
      { name: "宮古空港", cat: "港・交通", lat: 24.7824, lng: 125.2948,
        url: "",
        note: "本土・那覇からの便が発着。みやこ下地島空港も利用可" }
    ],
    shops: [],
    knowledge: [
      "島に川がなく海の透明度が高い「宮古ブルー」",
      "伊良部・池間・来間の3つの大橋で離島めぐりができる"
    ],
    tips: [
      "ビーチごとに監視・クラゲネットの有無が違う。遊泳情報を確認"
    ],
    logs: []
  },

  {
    id: "ishigaki", name: "石垣島", region: "沖縄の島", pref: "沖縄県",
    lat: 24.4, lng: 124.16,
    firstVisit: "2016", visits: 3, fav: true,
    summary: "八重山の拠点。川平湾のグラスボートと満点の星。",
    photos: [],
    spots: [
      { name: "米原キャンプ場", cat: "キャンプ場", lat: 24.4542, lng: 124.1888,
        url: "https://www.nap-camp.com/okinawa/10261",
        note: "米原ビーチ隣接の定番キャンプ場。営業は4〜12月" },
      { name: "伊野田オートキャンプ場", cat: "キャンプ場", lat: 24.4686, lng: 124.2525,
        url: "https://www.nap-camp.com/okinawa/10260",
        note: "東海岸の海辺キャンプ場。砂地のフリーサイト、ビーチ至近" },
      { name: "川平湾", cat: "観光", lat: 24.4528, lng: 124.1438,
        url: "https://www.okinawastory.jp/spot/1377",
        note: "ミシュラン三つ星の景勝地。グラスボートが人気、遊泳不可" },
      { name: "米原ビーチ", cat: "ビーチ", lat: 24.4542, lng: 124.1863,
        url: "https://yaeyama.or.jp/play/%E7%B1%B3%E5%8E%9F%E6%B5%B7%E5%B2%B8%E5%88%A9%E7%94%A8%E3%83%AB%E3%83%BC%E3%83%AB/",
        note: "サンゴと熱帯魚の人気シュノーケル海岸。離岸流に注意" },
      { name: "底地ビーチ", cat: "ビーチ", lat: 24.4661, lng: 124.1244,
        url: "https://www.okinawastory.jp/spot/600007516",
        note: "約1km続く遠浅の市指定海水浴場。夕日の名所" },
      { name: "フサキビーチ", cat: "ビーチ", lat: 24.3713, lng: 124.1142,
        url: "https://www.fusaki.com/",
        note: "リゾート前の天然ビーチ。桟橋越しの夕景が有名" },
      { name: "白保海岸", cat: "ビーチ", lat: 24.3544, lng: 124.2456,
        url: "https://www.okinawastory.jp/spot/600013230",
        note: "北半球最大級のアオサンゴ群落。シュノーケルの聖地" },
      { name: "玉取崎展望台", cat: "山・自然", lat: 24.4905, lng: 124.2789,
        url: "https://yaeyama.or.jp/%E7%8E%89%E5%8F%96%E5%B4%8E%E5%B1%95%E6%9C%9B%E5%8F%B0/",
        note: "太平洋と東シナ海を一望。ハイビスカス咲く絶景展望台" },
      { name: "平久保崎灯台", cat: "山・自然", lat: 24.6089, lng: 124.315,
        url: "https://yaeyama.or.jp/%E5%B9%B3%E4%B9%85%E4%BF%9D%E5%B4%8E/",
        note: "島最北端の岬。恋する灯台認定、紺碧の海を一望" },
      { name: "御神崎", cat: "山・自然", lat: 24.4525, lng: 124.0786,
        url: "https://yaeyama.or.jp/%E5%BE%A1%E7%A5%9E%E5%B4%8E/",
        note: "島最西端の断崖の岬。白い灯台と夕日の名所" },
      { name: "於茂登岳", cat: "山・自然", lat: 24.4272, lng: 124.1834,
        url: "https://ja.wikipedia.org/wiki/%E6%96%BC%E8%8C%82%E7%99%BB%E5%B2%B3",
        note: "標高526mの沖縄県最高峰。亜熱帯の森を登る往復約2時間" },
      { name: "バンナ公園", cat: "山・自然", lat: 24.3775, lng: 124.1596,
        url: "https://banna.jp/",
        note: "日本最南端の森林公園。エメラルドの海を見る展望台" },
      { name: "石垣島鍾乳洞", cat: "観光", lat: 24.3617, lng: 124.1544,
        url: "https://www.ishigaki-cave.com/",
        note: "20万年かけ形成、全長3.2km。日本最南端の鍾乳洞" },
      { name: "唐人墓", cat: "観光", lat: 24.3657, lng: 124.1133,
        url: "https://www.okinawastory.jp/spot/1371",
        note: "ロバート・バウン号事件の中国人犠牲者を祀る極彩色の墓" },
      { name: "グランヴィリオリゾート石垣島「華のゆ」", cat: "温泉", lat: 24.3575, lng: 124.124,
        url: "https://www.grandvrio-hotelresort.com/ishigaki/spa/",
        note: "島では希少な天然温泉の大浴場。露天風呂あり、宿泊者専用" },
      { name: "ユーグレナ石垣港離島ターミナル", cat: "港・交通", lat: 24.3376, lng: 124.1555,
        url: "https://www.city.ishigaki.okinawa.jp/soshiki/kowan/yugurenaisigakikouritoutaminaru/6957.html",
        note: "竹富・西表など八重山離島航路の玄関口" },
      { name: "南ぬ島石垣空港", cat: "港・交通", lat: 24.3956, lng: 124.245,
        url: "https://www.ishigaki-airport.co.jp/",
        note: "石垣島の空の玄関口。愛称は南ぬ島（ぱいぬしま）" },
      { name: "明石食堂", cat: "食事・店", lat: 24.5395, lng: 124.3002,
        url: "https://tabelog.com/okinawa/A4705/A470501/47000038/",
        note: "行列必至の八重山そば名店。とろとろソーキが絶品" },
      { name: "石垣やいま村", cat: "観光", lat: 24.4043, lng: 124.1444,
        url: "https://www.yaimamura.com/",
        note: "名蔵湾を望む日本最南端のテーマパーク。リスザルの森が人気" },
      { name: "ユーグレナモール", cat: "食事・店", lat: 24.3398, lng: 124.158,
        url: "https://www.euglenamall.com/",
        note: "日本最南端のアーケード商店街。土産店や飲食店が100店超" }
    ],
    shops: [],
    knowledge: [
          "八重山諸島(竹富・西表・小浜・波照間)へのフェリー拠点",
          "南十字星が見える数少ない日本の島"
    ],
    tips: [
          "離島ターミナルから各島へ。日帰りも組み合わせやすい",
          "米原ビーチはシュノーケルの定番、リーフカレントに注意"
    ],
    logs: []
  },

  {
    id: "iriomote", name: "西表島", region: "沖縄の島", pref: "沖縄県",
    lat: 24.35, lng: 123.8,
    firstVisit: "2018", visits: 2, fav: true,
    summary: "島の9割が亜熱帯ジャングル。イリオモテヤマネコの島。",
    photos: [],
    spots: [
      { name: "ミトレアキャンプ場", cat: "キャンプ場", lat: 24.405, lng: 123.8074,
        url: "https://mitorea.mariud.com/",
        note: "上原港から車5分、船浦湾を望む高台。温水シャワー完備" },
      { name: "南風見田キャンプ場", cat: "キャンプ場", lat: 24.2736, lng: 123.8329,
        url: "https://www.haimidakyanpu.com/",
        note: "日本最南端の老舗野営場。電気なし、満天の星空" },
      { name: "星の砂キャンプ場（ペンション星の砂）", cat: "キャンプ場", lat: 24.436, lng: 123.7771,
        url: "https://hoshinosuna.ne.jp/",
        note: "星砂の浜すぐ隣。ペンション併設で初心者も安心" },
      { name: "星砂の浜", cat: "ビーチ", lat: 24.4365, lng: 123.7772,
        url: "https://painusima.com/859/",
        note: "星形の砂で有名。遠浅で熱帯魚シュノーケルも" },
      { name: "トゥドゥマリの浜（月ヶ浜）", cat: "ビーチ", lat: 24.4236, lng: 123.7745,
        url: "",
        note: "三日月形の鳴き砂ビーチ。夕日の名所" },
      { name: "イダの浜", cat: "ビーチ", lat: 24.3398, lng: 123.7237,
        url: "",
        note: "船でしか行けない船浮集落先の秘境ビーチ" },
      { name: "南風見田の浜", cat: "ビーチ", lat: 24.2711, lng: 123.8353,
        url: "https://painusima.com/6914/",
        note: "島南端の約2kmロングビーチ。晴天時は波照間島も" },
      { name: "ピナイサーラの滝", cat: "山・自然", lat: 24.3819, lng: 123.8204,
        url: "https://painusima.com/849/",
        note: "落差約55mで沖縄県一。カヌー＋トレッキングで" },
      { name: "マリユドゥの滝", cat: "山・自然", lat: 24.3572, lng: 123.8032,
        url: "https://painusima.com/839/",
        note: "日本の滝百選。丸い滝壺が特徴の二段滝" },
      { name: "カンピレーの滝", cat: "山・自然", lat: 24.3551, lng: 123.8065,
        url: "https://painusima.com/854/",
        note: "「神々の座」の意。約200m続く緩やかな渓流瀑" },
      { name: "浦内川（ジャングルクルーズ）", cat: "山・自然", lat: 24.4031, lng: 123.7787,
        url: "https://painusima.com/844/",
        note: "沖縄県最長の川。遊覧船で滝群への玄関口" },
      { name: "仲間川（マングローブ）", cat: "山・自然", lat: 24.2797, lng: 123.8801,
        url: "https://painusima.com/819/",
        note: "日本最大のマングローブ林。大原港発遊覧船が人気" },
      { name: "バラス島", cat: "山・自然", lat: 24.4353, lng: 123.8172,
        url: "https://painusima.com/864/",
        note: "サンゴのかけらだけの無人島。シュノーケル名所" },
      { name: "大見謝ロードパーク", cat: "山・自然", lat: 24.3945, lng: 123.8641,
        url: "",
        note: "マングローブを間近に歩ける遊歩道と海の展望台" },
      { name: "由布島（亜熱帯植物楽園）", cat: "観光", lat: 24.3428, lng: 123.9336,
        url: "https://yubujima.com/",
        note: "水牛車で海を渡る亜熱帯植物楽園の島" },
      { name: "西表野生生物保護センター", cat: "観光", lat: 24.3308, lng: 123.9089,
        url: "https://iwcc.jp/",
        note: "イリオモテヤマネコ保護・展示の拠点。入館無料" },
      { name: "大原港（仲間港）", cat: "港・交通", lat: 24.2728, lng: 123.8849,
        url: "https://www.town.taketomi.lg.jp/administration/access/",
        note: "島東部の玄関口。石垣からの便は欠航が少ない" },
      { name: "上原港", cat: "港・交通", lat: 24.418, lng: 123.7998,
        url: "https://www.town.taketomi.lg.jp/administration/access/",
        note: "島西部の玄関口。冬は北風で欠航に注意" },
      { name: "白浜港", cat: "港・交通", lat: 24.3587, lng: 123.7454,
        url: "https://www.town.taketomi.lg.jp/administration/access/",
        note: "県道終点の西の玄関口。船浮・イダの浜へ渡る船が発着" },
      { name: "新八食堂", cat: "食事・店", lat: 24.4167, lng: 123.7996,
        url: "",
        note: "上原港徒歩3分の老舗食堂。八重山そばが人気" }
    ],
    shops: [],
    knowledge: [
          "面積の約90%が亜熱帯の原生林",
          "ピナイサーラの滝は沖縄県最大の落差"
    ],
    tips: [
          "カヌー＋トレッキングのツアーで滝上まで行ける",
          "夜は灯りが少なく星が濃い。懐中電灯必携"
    ],
    logs: []
  },

  {
    id: "yonaguni", name: "与那国島", region: "沖縄の島", pref: "沖縄県",
    lat: 24.46, lng: 123.00,
    firstVisit: "", visits: 0, fav: false,
    summary: "日本最西端。海底遺跡とDr.コトー診療所のロケ地。",
    photos: [],
    spots: [
      { name: "西崎（日本最西端の地）", cat: "観光", lat: 24.4502, lng: 122.9343,
        url: "",
        note: "日本最西端の碑と灯台。晴れた日は台湾が見えることも" },
      { name: "東崎", cat: "山・自然", lat: 24.4616, lng: 123.0435,
        url: "",
        note: "与那国馬が放牧される草原の岬。灯台と断崖" },
      { name: "立神岩", cat: "山・自然", lat: 24.4481, lng: 123.0261,
        url: "",
        note: "海にそそり立つ島のシンボルの奇岩" },
      { name: "サンニヌ台", cat: "山・自然", lat: 24.4541, lng: 123.0327,
        url: "",
        note: "岩畳の台地。軍艦岩を見下ろす展望台" },
      { name: "宇良部岳", cat: "山・自然", lat: 24.4529, lng: 123.0055,
        url: "",
        note: "標高231mの島最高峰。全島を見渡す" },
      { name: "海底遺跡ポイント", cat: "観光", lat: 24.436, lng: 123.0115,
        url: "",
        note: "謎の巨石海底地形。ダイビングか半潜水艇ツアーで" },
      { name: "Dr.コトー診療所", cat: "観光", lat: 24.4434, lng: 122.9839,
        url: "",
        note: "ドラマのロケセットが比川浜に残る（見学は開館日を確認）" },
      { name: "アヤミハビル館", cat: "観光", lat: 24.4565, lng: 123.0107,
        url: "",
        note: "世界最大級の蛾ヨナグニサン（アヤミハビル）の資料館" },
      { name: "ダンヌ浜", cat: "ビーチ", lat: 24.4652, lng: 122.9554,
        url: "",
        note: "岩に囲まれた小さな白砂の浜。写真映えする波打ち際のプール" },
      { name: "ナーマ浜", cat: "ビーチ", lat: 24.4483, lng: 122.9403,
        url: "",
        note: "久部良港横の穏やかな浜。夕日の名所" },
      { name: "久部良港", cat: "港・交通", lat: 24.4508, lng: 122.942,
        url: "",
        note: "石垣島からのフェリーよなくにが発着（週2便）" },
      { name: "与那国空港", cat: "港・交通", lat: 24.4673, lng: 122.9794,
        url: "",
        note: "石垣・那覇からの便が発着" }
    ],
    shops: [],
    knowledge: [
      "日本最西端の有人島。台湾まで約111km",
      "在来馬・与那国馬が島のあちこちに放牧されている"
    ],
    tips: [
      "フェリーは週2便で欠航も多い。飛行機利用が現実的",
      "海底遺跡は流れが速い上級ポイント。半潜水艇なら誰でも見られる"
    ],
    logs: []
  },

  {
    id: "hateruma", name: "波照間島", region: "沖縄の島", pref: "沖縄県",
    lat: 24.06, lng: 123.78,
    firstVisit: "", visits: 0, fav: false,
    summary: "日本最南端の有人島。南十字星とニシ浜の青。",
    photos: [],
    spots: [
      { name: "ニシ浜", cat: "ビーチ", lat: 24.0641, lng: 123.7614,
        url: "",
        note: "「ハテルマブルー」と称される島随一の白砂ビーチ" },
      { name: "ペムチ浜", cat: "ビーチ", lat: 24.0477, lng: 123.7793,
        url: "",
        note: "日本最南端の浜。流れが強く遊泳不可・眺めを楽しむ浜" },
      { name: "日本最南端之碑", cat: "観光", lat: 24.0479, lng: 123.7949,
        url: "",
        note: "有人島として日本最南端の地。高那崎の断崖のそば" },
      { name: "星空観測タワー", cat: "観光", lat: 24.0499, lng: 123.7977,
        url: "",
        note: "南十字星の観測拠点。開館日・時間は要確認" },
      { name: "高那崎", cat: "山・自然", lat: 24.0499, lng: 123.8052,
        url: "",
        note: "太平洋の荒波が打ち付ける隆起サンゴの断崖" },
      { name: "コート盛", cat: "観光", lat: 24.0636, lng: 123.7744,
        url: "",
        note: "琉球王朝時代の火番所（遠見台）。集落と海を一望" },
      { name: "下田原城跡", cat: "観光", lat: 24.0691, lng: 123.7781,
        url: "",
        note: "15世紀ごろの城跡。国指定史跡" },
      { name: "波照間港", cat: "港・交通", lat: 24.0673, lng: 123.7658,
        url: "",
        note: "石垣島からの高速船が発着。冬場は欠航率が高い" },
      { name: "波照間空港", cat: "港・交通", lat: 24.0597, lng: 123.8057,
        url: "",
        note: "島東部の小さな空港。小型機の便が発着" }
    ],
    shops: [],
    knowledge: [
      "日本最南端の有人島。12〜6月は南十字星が見える",
      "高速船は外洋を渡るため欠航が多い。帰りの便に余裕を"
    ],
    tips: [
      "ニシ浜は監視員がいない。沖のリーフ外に出ない",
      "黒糖と幻の泡盛「泡波」が名物"
    ],
    logs: []
  },

  {
    id: "sado", name: "佐渡島", region: "新潟の島", pref: "新潟県",
    lat: 38.05, lng: 138.4,
    firstVisit: "2014", visits: 3, fav: false,
    summary: "たらい舟と金山。離島とは思えない大きさと歴史。",
    photos: [],
    spots: [
      { name: "素浜キャンプ場", cat: "キャンプ場", lat: 37.8483, lng: 138.2712,
        url: "https://www.visitsado.com/spot/detail0869/",
        note: "島最大・全長4kmの素浜海岸に隣接する夏季営業の海辺キャンプ場" },
      { name: "二ツ亀キャンプ場", cat: "キャンプ場", lat: 38.3297, lng: 138.4874,
        url: "https://www.visitsado.com/spot/detail0270/",
        note: "二ツ亀を望む絶景サイト。透明度抜群の海がすぐそば" },
      { name: "入崎キャンプ場", cat: "キャンプ場", lat: 38.1976, lng: 138.3269,
        url: "https://www.visitsado.com/spot/detail0870/",
        note: "外海府の入崎海水浴場に隣接。磯遊びや磯釣りも楽しめる" },
      { name: "ist-Sado（旧佐渡関岬オートキャンプ場）", cat: "キャンプ場", lat: 38.2488, lng: 138.4017,
        url: "https://ist-field.com/sado/",
        note: "関岬の海抜100m高台。サウナ併設の複合キャンプ場、冬季休業" },
      { name: "窪田キャンプ場", cat: "キャンプ場", lat: 38.0042, lng: 138.3101,
        url: "https://www.visitsado.com/spot/detail0274/",
        note: "真野湾沿いの松林サイト。市街地近くで買い物に便利" },
      { name: "ドンデン高原ロッジ キャンプ場", cat: "キャンプ場", lat: 38.1383, lng: 138.3904,
        url: "https://donden-sanso.jp/",
        note: "標高890mの高原サイト。満天の星と佐渡両湾の大展望、4〜11月営業" },
      { name: "松ヶ崎ヒストリーパーク", cat: "キャンプ場", lat: 37.9204, lng: 138.4997,
        url: "https://www.visitsado.com/spot/detail0001/",
        note: "鴻ノ瀬鼻灯台と海を目前にする市営フリーサイト。4月末〜10月開設" },
      { name: "佐和田海水浴場", cat: "ビーチ", lat: 38.0013, lng: 138.3155,
        url: "https://www.visitsado.com/spot/detail0402/",
        note: "遠浅で波穏やか。飲食店や宿が近い町なかビーチ" },
      { name: "佐渡八幡温泉 八幡館", cat: "温泉", lat: 37.9868, lng: 138.345,
        url: "https://www.yahatakan.com/",
        note: "佐渡随一の湧出量を誇る源泉かけ流し。皇室ゆかりの名宿" },
      { name: "大野亀", cat: "山・自然", lat: 38.321, lng: 138.4616,
        url: "https://www.visitsado.com/spot/detail0133/",
        note: "海に突き出す標高167mの一枚岩。6月はトビシマカンゾウ群生" },
      { name: "二ツ亀", cat: "山・自然", lat: 38.3307, lng: 138.4862,
        url: "https://www.visitsado.com/spot/detail0134/",
        note: "亀がうずくまる姿の島。ミシュラン二つ星、島随一の透明度" },
      { name: "尖閣湾揚島遊園", cat: "山・自然", lat: 38.0937, lng: 138.2505,
        url: "https://sado-ageshima.com/",
        note: "断崖絶壁が続く景勝地。海中透視船で湾内遊覧できる" },
      { name: "史跡佐渡金山", cat: "観光", lat: 38.0417, lng: 138.2561,
        url: "https://www.sado-kinzan.com/",
        note: "世界遺産「佐渡島の金山」。江戸と明治の坑道を見学" },
      { name: "北沢浮遊選鉱場跡", cat: "観光", lat: 38.0369, lng: 138.2414,
        url: "https://www.visitsado.com/spot/detail0091/",
        note: "東洋一と呼ばれた選鉱場跡。ラピュタ風の巨大遺構と夜間ライトアップ" },
      { name: "宿根木", cat: "観光", lat: 37.8067, lng: 138.2432,
        url: "https://shukunegi.com/",
        note: "北前船で栄えた船大工の集落。国の重伝建地区" },
      { name: "矢島・経島（たらい舟）", cat: "観光", lat: 37.8068, lng: 138.266,
        url: "https://www.visitsado.com/spot/detail0152/",
        note: "赤い太鼓橋の架かる入り江。名物たらい舟体験ができる" },
      { name: "トキの森公園", cat: "観光", lat: 38.0377, lng: 138.4219,
        url: "https://www.city.sado.niigata.jp/site/tokinomori/1161.html",
        note: "特別天然記念物トキを間近で観察できる保護・展示施設" },
      { name: "しまふうみ", cat: "食事・店", lat: 37.94, lng: 138.3073,
        url: "https://www.primosado.jp/shimafumi/",
        note: "真野湾を一望する絶景ベーカリーカフェ。天然酵母パンが人気" },
      { name: "両津港", cat: "港・交通", lat: 38.0817, lng: 138.4381,
        url: "https://www.sadokisen.co.jp/",
        note: "島の玄関口。新潟港からジェットフォイルとカーフェリー" },
      { name: "小木港", cat: "港・交通", lat: 37.8163, lng: 138.2822,
        url: "https://www.sadokisen.co.jp/",
        note: "南部の玄関口。直江津航路が発着、たらい舟乗り場至近" }
    ],
    shops: [],
    knowledge: [
          "離島では沖縄本島に次ぐ面積",
          "佐渡金山は江戸幕府の財政を支えた"
    ],
    tips: [
          "新潟港からカーフェリーで約2.5時間、車を載せると自由度が高い",
          "宿根木の集落と矢島・経島のたらい舟は外せない"
    ],
    logs: []
  }
];
